### ISSUE TITLE
TypeError: get_color_scale() got an unexpected keyword argument 'font_path'

### ISSUE THREAD

**Issue by morethanbooks** [cligs/tmw#14] opened 2015-09-08 09:51 UTC
When I try to use tmw.make_wordle_from_mallet, it appeared an error:
get_color_scale() got an unexpected keyword argument 'font_path'

I solved it commenting in tmw this line:
plt.imshow(wordcloud.recolor(color_func=get_color_scale, random_state=3))

I don't know which is the actual problem...

**Comment by christofs** [comment] 2015-09-08 13:18
I cannot reproduce this error. Could you update the word_cloud code first and check whether the error remains?

**Comment by christofs** [comment] 2015-10-21 13:44
Finally found the problem. Should be fixed now. Maybe you can test it?

**Closed as completed** 2015-10-21 14:45 UTC
Labels: bug
